allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  es5-ext: true
  fsevents: true
  prisma: true
  sharp: true
  uglifyjs-webpack-plugin: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@better-auth/core@1.6.12'
  - '@better-auth/drizzle-adapter@1.6.12'
  - '@better-auth/kysely-adapter@1.6.12'
  - '@better-auth/memory-adapter@1.6.12'
  - '@better-auth/mongo-adapter@1.6.12'
  - '@better-auth/prisma-adapter@1.6.12'
  - '@better-auth/telemetry@1.6.12'
  - better-auth@1.6.12
